name: Publish

on:
  release:
    types: [published]

jobs:
  packages:
    runs-on: ubuntu-latest
    name: Publish packages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      # TODO Add typings validation

      - name: Publish to NPM
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          yarn publish-packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
