name: Publish

on:
  release:
    types: [published]

jobs:
  packages:
    runs-on: ubuntu-latest
    name: Publish packages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Publish to NPM
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          yarn publish-packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
